### ISSUE TITLE
Arm Cortex-M support?

### ISSUE THREAD

**Issue by beriberikix** [JohnSully/libwasm#1]
Current CMake file targets x64. Would it be possible to target Cortex M 32bit embedded chipsets using the [GNU Arm Embedded Toolchain](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm).

**Comment by JohnSully** [comment]
libwasm works by translating wasm assembly to raw machine code.  Right now it only emits x64 machine code.  Support for ARM is planned but its a non-trivial work item.  Recompiling with an ARM toolchain is insufficient.

**Comment by JohnSully** [comment]
Tracking as a project.
https://github.com/JohnSully/libwasm/projects/1
